"""


Module __init__

This module serves as the initializer for a package providing access to key abstractions such as Clock, Future, and Queue. It imports the protocols for these components, which can be implemented to provide the functionality dictated by their interface. This module acts as the facade to the package's functionalities, allowing users to access different asynchronous utilities.

Classes:
    Clock (typing.Protocol): A protocol to represent clock utilities, providing a current time method.
    Future (typing.Protocol[T]): A protocol for future objects, representing asynchronous execution that may or may not have completed.
    Queue (typing.Protocol[T]): A protocol for queue objects, defining basic queue operations.

Note: Documentation automatically generated by https://undoc.ai
"""
from .clock import Clock
from .future import Future
from .queue import Queue
