"""

A module initializer that imports the PlantUMLGenerator class from the plantuml_generator module within the plantuml package.

This module makes the PlantUMLGenerator class available at the package level, allowing users to instantiate an object of this class directly from the package namespace without needing to reference the plantuml_generator module.

Note: Documentation automatically generated by https://undoc.ai
"""
from .plantuml.plantuml_generator import PlantUMLGenerator
