@startuml
skinparam linetype ortho
skinparam arrowColor white
skinparam backgroundColor #000000
skinparam ActivityBarColor white
<style>
circle {
    backgroundColor white
}
</style>
skinparam State {
    backgroundColor black
    FontColor white
    borderColor white
}
 state "AsyncStateMachine" as AsyncStateMachine {
    }
 note top of AsyncStateMachine: "Asynchronous state machine implementation that handles behaviors and state transitions.\n\n    This class extends the generic Behavior and CompositeState classes to facilitate\n    concurrent operations within the state machine. The AsyncStateMachine allows for the\n    definition of states and transitions and manages the asynchronous execution of behavior\n    activities triggered by events.\n\n    Attributes:\n        submachine_state (State): The reference to the submachine state if this state machine\n                                  is used as a submachine within another state machine.\n\n    Properties:\n        state (tuple[State]): A tuple containing references to all the currently active states\n                              within the state machine.\n    " @enduml
