"""

Module `__init__` of the package.

This module initializes the package and imports the `Clock` class from the `clock` submodule, making it accessible when the package is imported.

Attributes:
    Clock (class): A class that represents a mockable clock with an adjustable time scale.

Note: Documentation automatically generated by https://undoc.ai
"""
from .clock import Clock
